### ISSUE TITLE
Implicit get after put with dynamic source

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/bosh-deployment-resource#11]
Because dynamic source configuration is only accepted for `put` operations, it's possible to do a `put` with one source and then an implicit `get` with a different source. For example, after a `put` with a source file that includes a dynamic certificate, concourse will run a `get` against the same resource, but without the certificate, causing the `get` to fail. The implicit `get` could even check a different director than the `put` that triggers it, which would be confusing. It seems like it would make more sense to allow something like this:

```yaml
...
put: some-bosh-deployment
  params:
    source_file: path/to/source/file
  get_params:
    source_file: path/to/source/file
...
```

But because dynamic source configuration isn't supported on `get`, this doesn't work. Would you be open to changing this behavior, or am I missing a better way to make sure the implicit `get` is actually fetching the deployment touched by the `put`?
