### ISSUE TITLE
vars_file fails to unmarshal yml 

### ISSUE THREAD

**Issue by aclevername** [cloudfoundry/bosh-deployment-resource#23]
We have configured a `put` to the resource to try and deploy a manifest that uses bosh2 cli variables (e.g. `((bosh.username))`). Reading the documentation it describes the `vars_file` as a way of configuring these variables, so we configured it like so:

```
  - put: my-bosh
    params:
      manifest: manifests/manifest.yml
      vars_files:
        secrets/secrets.yml
```

When running the pipeline we get the following error: `Invalid parameters: Invalid parameters: json: cannot unmarshal string into Go value of type []string`. Does this mean that the `vars_file` has to be JSON?
