### ISSUE TITLE
bosh cli v1 on the new version of bosh-deployment-resource ?

### ISSUE THREAD

**Issue by jyriok** [cloudfoundry/bosh-deployment-resource#42]
hello 
i want use the " cloudfoundry/bosh-deployment-resource" version, for bosh cli V2 
so for it, i add resources :
```
- name: bosh-deployment
 type: docker-image
 source:
   repository: cloudfoundry/bosh-deployment-resource
```

but when i add my source info :

```
- name: staging
 type: bosh-deployment
 source:
   deployment: CF-deployment
   target: https://10.10.10.8:25555
   client: xxxxx
   client_secret: xxxxxx
```

and push it on my concourse and launch, i've error from the old version of  bosh-deployment-resource (the bosh v1 one)

```
/usr/lib/ruby/gems/2.5.0/gems/bosh_deployment_resource-0.0.1/lib/bosh_deployment_resource/auth.rb:14:in `parse': source must include either username/password or client_id/client_secret (RuntimeError)
    from /usr/lib/ruby/gems/2.5.0/gems/bosh_deployment_resource-0.0.1/bin/bdr_out:22:in `<top (required)>'
    from /opt/resource/out:23:in `load'
    from /opt/resource/out:23:in `<main>'
```

  seem i use the deprecated version of bosh-deployment-resource  ( concourse/bosh-deployment-resource one ) for bosh v1 ...  :-/ any idea why  ?
